### ISSUE TITLE
Did you see the PySimpleGUI User Settings APIs?

### ISSUE THREAD

**Issue by PySimpleGUI** [econ-RUBICS/RUBICS#2]
I noticed in your documentation and code that you have a lot of user settings that are in JSON format.  Did you see the PySimpleGUI User Settings API that simplifies accessing JSON files and .INI files?

Here's the documentation on that interface:
https://www.pysimplegui.org/en/latest/#user-settings-api

There are a lot of Demo Programs to show the various ways of accessing the APIs.   The User Settings API is used heavily in applications provided by the PySimpleGUI project, such as the Demo Browser.

![image](https://github.com/econ-RUBICS/RUBICS/assets/46163555/1a6d31c2-0a79-499c-8afb-cd1137b5938c)

The upcoming PySimpleGUI 5 release expands the settings API.

**Comment by econ-RUBICS** [comment]
Hi Mike, 

I had a look at the built-in user settings functionality when I started, but for my purposes I wanted something that wrote to a specific kind of template. However, I definitely want to be able to build-in a way for users to save a particular session, so that's on the agenda for the future. So I will be looking into incorporating this.

Cheers! 
Sam
